---
title: "IPF_paper_figureS2"
date: "`r Sys.Date()`"
output:
  html_document: 
    code_folding: hide
    number_sections: yes
    theme: united
    toc_float: yes
  pdf_document:
    toc: yes
---


# general settings

```{r}
load_packages = c("Seurat","ggplot2","magrittr","tidyr","dplyr","stringr")
lapply(load_packages,library,character.only=TRUE)

working.dir = "/home/jyu/rstudio/"

ms_dir = paste0(working.dir,"/IPF_manuscript/manuscriptV3/figures")
ms_date = "20230921"

rm(load_packages)
```

## color

### IPF stages

```{r}
stage_color = c("Control" = "grey",
                "Early-IPF" = "#076B94",
                "Advanced-IPF" = "#E0B32D"
                )
```

### cluster color

```{r}
major_cluster_color = c("0" = "#344e41",
                             "4_0" = "#FF1493",
                         "4_1" = "#48cae4",
                         "4_2" = "#ffafcc",
                             "5" = "#A0522D",
                             "6" = "#BDE4C8",
                             "7" = "#a7c957",
                             "8" = "#73BCEB",
                             "9" = "#C2AACB",
                             "10" = "#00b4d8",
                             "11" = "#467599",
                             "12" = "#7B68EE",
                             "13" = "#6a994e",
                             "14" = "#5C2C31",
                             "15" = "#6C79D4",
                             "16" = "#8FA0C6",
                             "17" = "#E9967A",
                             "19" = "#ffd500",
                             "20" = "#31572c",
                             "21" = "#252422",
                             "22" = "#D096A8",
                             "24" = "#0000FF")
```


## load seurat object

```{r}
ipf_seu = readRDS(file=paste0(working.dir,"/IPF_manuscript/data/ILD_combined_sct_rpca20230720.rds"))

ipf_seu$IPFgroup = factor(ipf_seu$IPFgroup,levels = c("Control","Early-IPF","Advanced-IPF"))

## export tables4
# 
# tmpdata = table(ipf_seu$pnt_in_paper,ipf_seu$subcluster)
# tmpdata1 = as.matrix.data.frame(tmpdata)
# rownames(tmpdata1) = rownames(tmpdata)
# colnames(tmpdata1) = colnames(tmpdata)
# 
# write.csv(tmpdata1,paste0(working.dir,"/IPF_manuscript/manuscript/tables4.csv"))
# 
# rm(tmpdata,tmpdata1)
```



# figure S2A

```{r}

ipf_seu$cohort = ifelse(ipf_seu$source == "Kevin_COPD", "Bassler_control",as.character(ipf_seu$IPFgroup))
ipf_seu$cohort = ifelse(ipf_seu$cohort == "Control", "Present study_control",as.character(ipf_seu$cohort))

ipf_seu$cohort = factor(ipf_seu$cohort,levels = c("Bassler_control","Present study_control","Early-IPF","Advanced-IPF"))

Idents(ipf_seu) = "subcluster"

ipf_seu = RenameIdents(ipf_seu,
                          "0" = "Macrophage",
                             "4_0" = "Macrophage",
                             "4_1" = "Macrophage",
                             "4_2" = "Macrophage",
                             "5" = "T/NK cell",
                             "6" = "Macrophage",
                             "7" = "Macrophage",
                             "8" = "Macrophage",
                             "9" = "T/NK cell",
                             "10" = "Macrophage",
                             "11" = "Macrophage",
                             "12" = "Neutrophil",
                             "13" = "Macrophage",
                             "14" = "T/NK cell",
                             "15" = "Epithelial cell",
                             "16" = "Epithelial cell",
                             "17" = "DC",
                             "19" = "DC",
                             "20" = "Macrophage",
                             "21" = "Mast cell",
                             "22" = "Eosinophil",
                             "24" = "Epithelial cell")

seurat_cluster_color =  c("Macrophage" = "#8DD3C7",
                             "DC" = "#E9967A",
                             "Neutrophil" = "#7B68EE",
                             "Eosinophil" = "purple",
                             "Mast cell" = "red",
                             "T/NK cell" = "green",
                             "Epithelial cell" = "black")

pdf(file = paste0(ms_dir,"/figs2a_major_umap_bygroup_",ms_date,".pdf"),paper = "a4",width = 7.1,height = 2 )

p = DimPlot(ipf_seu,dims = c(1,3),
        split.by = "cohort",
        # group.by = "major",
        cols = seurat_cluster_color,
        raster = TRUE,repel = TRUE,raster.dpi = c(1024,1024),pt.size = 5)+
        # label = TRUE,label.size = 2.7)+
  # labs(title = "All cells (n=72,360)")+
  # geom_text(data=data.frame(),aes(label = "71,360 cells",x=-Inf,y=Inf),hjust=-0.1,vjust=21,size=3)+
  # ggrepel::geom_text_repel()+
  theme(axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_text(size=7),
        strip.text = element_text(size = 7,colour = "black",face = "plain"),
        plot.title = element_text(hjust=0.5,face = "plain",size = 8),
        panel.border = element_rect(color = "black",size=0.3,fill = NA),
        legend.text = element_text(size = 7,colour = "black"),
        legend.text.align = 0,
        legend.key.size = unit(0.4,"cm"),
        legend.title = element_text(size = 8))
        # legend.position = "none")


plot(p)

dev.off()

p

rm(p)
```

# figure S2b

```{r}
single_live_color = c("0" = "#344e41",
                             "4" = "#FF1493",
                             "5" = "#A0522D",
                             "6" = "#BDE4C8",
                             "7" = "#a7c957",
                             "8" = "#73BCEB",
                             "9" = "#C2AACB",
                             "10" = "#00b4d8",
                             "11" = "#467599",
                             "12" = "#7B68EE",
                             "13" = "#6a994e",
                             "14" = "#5C2C31",
                             "15" = "#6C79D4",
                             "16" = "#8FA0C6",
                             "17" = "#E9967A",
                             "19" = "#ffd500",
                             "20" = "#31572c",
                             "21" = "#252422",
                             "22" = "#D096A8",
                             "24" = "#0000FF")

single_live_label = c("0" = expression(Alveolar*"-"*M*phi1*(0)),
                             "4" = expression(VCAN^"+"*M*phi1*(4)),
                             "5" = "T cell(5)",
                             "6" = expression(S100A11^"+"*M*phi1*(6)),
                             "7" = expression(MKI67^"+"*M*phi1*(7)),
                             "8" = expression(CXCL10^"+"*M*phi1*(8)),
                             "9" = "T cell(9)",
                             "10" = expression(TNFAIP6^"+"*M*phi1*(10)),
                             "11" = expression(NEAT1^"+"*M*phi1*(11)),
                             "12" = "Neutrophil(12)",
                             "13" = expression(MKI67^"+"*M*phi1*(13)),
                             "14" = "NK cell(14)",
                             "15" = "Goblet cell(15)",
                             "16" = "Ciliated cell(16)",
                             "17" = "DC(17)",
                             "19" = "pDC(19)",
                             "20" = expression(MKI67^"+"*M*phi1*(20)),
                             "21" = "Mast cell(21)",
                             "22" = "Eosinophil(22)",
                             "24" = "Epithelial cell(24)")
ipf_seu$seurat_clusters = factor(ipf_seu$seurat_clusters,levels = c(0,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19,20,21,22,24))

pdf(file = paste0(ms_dir,"/figs2b_subcluster_umap_",ms_date,".pdf"),paper = "a4",width = 4.5,height = 2.5 )

p = DimPlot(ipf_seu,
        dims = c(1,3),
        group.by = "seurat_clusters",
        # split.by = "major",
        # cols = color_majorcelltype,
        cols = single_live_color,
        # ncol = 3,
        # shuffle = TRUE,
        raster = TRUE,
        raster.dpi = c(2048,2048),
        label = TRUE,
        repel = TRUE,
        pt.size = 3,
        label.size = 2.7)+
  # labs(title = "Macrophage (n=56,627)")+
  # geom_text(data=data.frame(),aes(label = "56,627 cells",x=-Inf,y=Inf),hjust=-0.1,vjust=19,size=3)+

      theme(axis.line = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.title = element_text(size=8),
        plot.title = element_blank(),
        panel.border = element_rect(color = "black",size=0.5,fill = NA),
        legend.text = element_text(size = 7,colour = "black"),
        legend.text.align = 0,
        legend.key.size = unit(0.3,"cm"),
        legend.title = element_text(size = 8),
        legend.box.margin = margin(0,0,0,-11)
        )+
  scale_color_manual(name = "Cluster",
                     labels = single_live_label,
                     values = single_live_color)+
  guides(color=guide_legend(ncol=2))

plot(p)

dev.off()

p

rm(p)
```

# figure S2c

```{r}
# prediction score is from addmodulescore
# install.packages("DescTools")
library(DescTools)
library(ComplexHeatmap)

travaglini_prediction = read.csv(file=paste0(working.dir,"/IPF_manuscript/manuscriptV3/meta_data/travaglini_clusters_prediction_score.csv"))
tmp_prediction = colnames(travaglini_prediction)[colnames(travaglini_prediction) %like% "%travaglini%"]

tmp_data = cbind(travaglini_prediction$seurat_clusters,travaglini_prediction[,c(tmp_prediction)])


colnames(tmp_data)[1] = "seurat_clusters"
# tmp_data$seurat_clusters = paste0("cluster",tmp_data$seurat_clusters)

## merge cluster4 subclusters
# tmp_data$seurat_clusters = ifelse(tmp_data$seurat_clusters %in% c("4_1:RNASE1+Mac","4_2:SPP1+Mac","4_0:VCAN+Mac"),"4:VCAN+Mac",tmp_data$seurat_clusters)

tmp_data = tmp_data%>%
  group_by(seurat_clusters)%>% 
  summarise(across(tmp_prediction, mean)) %>% 
  as.data.frame()
rownames(tmp_data) = tmp_data$seurat_clusters
tmp_data = tmp_data[,-1]

colnames(tmp_data) = str_replace(colnames(tmp_data),pattern = "travaglini","")
colnames(tmp_data) = str_replace_all(colnames(tmp_data),pattern = "\\."," ")
colnames(tmp_data) = str_sub(colnames(tmp_data), 1, str_length(colnames(tmp_data))-1)


tmp_data = tmp_data[c("6","10","8","11","7","13","20","4","17","19","22","21","12","5", "9","14","15", "16", "24"),
                    c("Macrophage","Intermediate Monocyte","Myeloid Dendritic Type 1","Plasmacytoid Dendritic","Basophil Mast 1","Neutrophil","CD4  Naive T","Natural Killer T","Goblet","Ciliated" ,"Alveolar Epithelial Type 2" )]

# tmp_data = tmp_data[c("6:S100A11+Mac","10:TNFAIP6+Mac","8:CXCL10+Mac","11:NEAT1+Mac","7:MKI67+Mac","13:MKI67+Mac","20:MKI67+Mac","4:VCAN+Mac","17:DC","19:pDC","22:Eosinophil","21:Mast","12:Neutrophil","5:Tcell", "9:Tcell","14:NK","15:Goblet", "16:Ciliated", "24:Epithelial"),
#                     c("Macrophage","Intermediate Monocyte","Myeloid Dendritic Type 1","Plasmacytoid Dendritic","Basophil Mast 1","Neutrophil","CD4  Naive T","Natural Killer T","Goblet","Ciliated" ,"Alveolar Epithelial Type 2" )]

plot_rowname = c(expression(S100A11^"+"*M*phi1*(6)),expression(TNFAIP6^"+"*M*phi1*(10)),expression(CXCL10^"+"*M*phi1*(8)),expression(NEAT1^"+"*M*phi1*(11)),expression(MKI67^"+"*M*phi1*(7)),expression(MKI67^"+"*M*phi1*(13)),expression(MKI67^"+"*M*phi1*(20)),expression(VCAN^"+"*M*phi1*(4)),"DC(17)","pDC(19)","Eosinophil(22)","Mast cell(21)","Neutrophil(12)","T cell(5)","T cell(9)","NK cell(14)","Goblet cell(15)","Ciliated cell(16)","Epithelial cell(24)")

plot_colname = c("Macrophage","Intermediate monocyte","Myeloid dendritic type 1","Plasmacytoid dendritic cell","Basophil/Mast cell","Neutrophil","CD4+ naive T cell","Natural killer T cell","Goblet cell","Ciliated cell" ,"Alveolar epithelial type 2")


pdf(paste0(ms_dir,"/figs2c_travaglini_compare_",ms_date,".pdf"),paper = "a4",width = 2.8,height = 4.5 )

col_fun = circlize::colorRamp2(c(-4, 0, 4), c("#a8dadc","white","#9d0208"))

ht1 = ComplexHeatmap::Heatmap(scale(tmp_data),
                        name = "Scaled prediction score",
                        col = col_fun,
                        cluster_rows = FALSE,
                        cluster_columns = FALSE,
                        row_names_gp = grid::gpar(fontsize = 8),
                        row_labels = plot_rowname,
                        row_title_gp = grid::gpar(fontsize = 8),
                        row_names_side = "right",
                        row_title = "Clusters from present study",
                        column_names_gp = grid::gpar(fontsize = 8),
                        column_title_gp = grid::gpar(fontsize = 8),
                        column_names_side = "top",
                        column_title = "Clusters from Travaglini et al",
                        border_gp = gpar(col = "black", lty = 1),
                        heatmap_legend_param = list(color_bar = "continuous", legend_direction = "horizontal",
                                                    legend_width = unit(2.5, "cm"),title_gp = gpar(col = "black", fontsize = 8),
                                                    legend_gp = gpar(col = "black", fontsize = 8))
                        )
ComplexHeatmap::draw(ht1, heatmap_legend_side = "bottom")

dev.off()

ComplexHeatmap::draw(ht1, heatmap_legend_side = "bottom")
rm(tmp_prediction,tmp_data,col_fun,ht1,travaglini_prediction,plot_rowname,plot_colname)


```

# figure S2d

```{r}
run1to4_ck_ipf_n_copd_ck_deg = read.csv(file = paste0(working.dir,"/IPF_manuscript/manuscriptV3/meta_data/ILD_combined_sct_rpca.DEG.csv"),sep = ",")
tmp_genes = run1to4_ck_ipf_n_copd_ck_deg  %>% group_by(cluster) %>% top_n(n = 3, wt = avg_log2FC)
tmp_genes = tmp_genes[! tmp_genes$cluster %in% c(1,2,3,18,23),]

tmp_genes = tmp_genes[order(tmp_genes$avg_log2FC,decreasing = TRUE),]

tmp_genes$cluster = factor(tmp_genes$cluster,levels = c(0,4,5,6,7,8,9,10,11,12,13,14,15,16,17,19,20,21,22,24) )
tmp_genes = tmp_genes[order(tmp_genes$cluster,decreasing = TRUE),]

pdf(paste0(ms_dir,"/figs2d_seuratclusters_deg_",ms_date,".pdf"),paper = "a4",width = 3.5,height = 6 )

p = DotPlot(ipf_seu,features = unique(tmp_genes$gene),
        group.by = "seurat_clusters",assay = "RNA")

p = ggplot(p$data,aes(x=features.plot,y=id))+
  geom_point(aes(size=pct.exp,color=avg.exp.scaled))+
  scale_y_discrete(labels = single_live_label)+
  scale_color_gradientn(colours  = c("#a8dadc","white","#9d0208"))+
  coord_flip()+
  xlab("")+
  ylab("")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.text = element_text(size = 6),
        axis.line = element_blank(),
        # axis.ticks.y = element_blank(),
        # axis.text.y = element_blank(),
        panel.border = element_rect(color = "black",size=0.8,fill = NA),
        legend.position = "left",
        legend.justification='bottom',
        legend.text = element_text(size = 8,colour = "black"),
        legend.title = element_text(size = 8,colour = "black"),
        legend.box = "vertical",
        legend.box.margin = margin(-20,-20,-20,-11))+
  guides(size = guide_legend(order = 2,title = "% of exp. cells"),
         color = guide_colorbar(order = 2,title = "Gene expression",barwidth = 0.3,barheight = 3))
plot(p)
dev.off()
p
rm(run1to4_ck_ipf_n_copd_ck_deg,tmp_genes,p)
```

# Figure S2E

## load seurat object

```{r}
# Idents(ipf_seu) = "seurat_clusters"
# ipf_seu_mac = subset(ipf_seu,idents = c(0,4,6,7,8,10,11,13,20)) 
# ipf_seu_mac <- RunUMAP(ipf_seu_mac,
#                             reduction = "pca",
#                             dims = 1:30,
#                             n.neighbors = 30,
#                             min.dist = 0.000001,
#                             n.components = 3,
#                             a = 1,
#                             b = 0.9,
#                             spread = 4)
# 
# DimPlot(ipf_seu_mac,dims = c(2,3))
# 
# saveRDS(ipf_seu_mac, file = paste0(working.dir,"/IPF_manuscript/data/ILD_combined_sct_rpca20230720_mac.rds"))
ipf_seu_mac = readRDS(file=paste0(working.dir,"/IPF_manuscript/data/ILD_combined_sct_rpca20230720_mac.rds"))

Idents(ipf_seu_mac) = "subcluster"

##use same colors for cluster 7, 13, 20
mac_color = c("0" = "#344e41",
                             "4_0" = "#FF1493",
                         "4_1" = "#48cae4",
                         "4_2" = "#ffafcc",
                             "6" = "#BDE4C8",
                             "7" = "#6a994e",
                             "8" = "#73BCEB",
                             "10" = "#00b4d8",
                             "11" = "#467599",
                             "13" = "#6a994e",
                             "20" = "#6a994e")


mac_label = c("0" = expression(Alveolar*"-"*M*phi1*(0)),
                             "4_0" = "Monocyte(4_0)",
                             "4_1" = expression(RNASE1^"+"*M*phi1*(4*"_"*1)),
                             "4_2" = expression(SPP1^"+"*M*phi1*(4*"_"*2)),
                             "6" = expression(S100A11^"+"*M*phi1*(6)),
                             "7" = expression(MKI67^"+"*M*phi1*(7*","*13*","*20)),
                             "8" = expression(CXCL10^"+"*M*phi1*(8)),
                             "10" = expression(TNFAIP6^"+"*M*phi1*(10)),
                             "11" = expression(NEAT1^"+"*M*phi1*(11)),
                             "13" = expression(MKI67^"+"*M*phi1*(7*","*13*","*20)),
                             "20" = expression(MKI67^"+"*M*phi1*(7*","*13*","*20)))

```
## export for scenic analysis

### include prolif

```{r}
# devtools::install_github("aertslab/SCopeLoomR")
# library(SCopeLoomR)
# library(SCENIC)
# library(tidyr)
# 
# ## take 100 cells per cluster
# 
# num_cells = ipf_seu_mac@meta.data 
# num_cells$cellid = rownames(ipf_seu_mac@meta.data)
# 
# num_cells = num_cells %>% group_by(subcluster) %>% slice_sample(n=100)
# tmp_seurat = ipf_seu_mac[,num_cells$cellid]
# 
# 
# ## use raw counts as input for scenic
# loom = SCopeLoomR::build_loom(paste0(working.dir,"/IPF_manuscript/data/ILD_combined_sct_rpca20230720_mac_rawcounts_100persubcluster_scenic.loom"),
#                   dgem=tmp_seurat@assays$RNA@counts)
# 
# # loom = add_cell_annotation(loom,tmp_seurat@meta.data)
# 
# close_loom(loom)
```

### rmvprolif

```{r}
# # devtools::install_github("aertslab/SCopeLoomR")
# library(SCopeLoomR)
# # library(SCENIC)
# library(tidyr)
# 
# ## take 100 cells per cluster
# 
# num_cells = ipf_seu_mac@meta.data
# num_cells$cellid = rownames(ipf_seu_mac@meta.data)
# 
# num_cells = num_cells %>% group_by(subcluster) %>% slice_sample(n=100)
# 
# ### rmv prolif cells
# 
# num_cells = num_cells[!num_cells$seurat_clusters %in% c(7,13,20),]
# tmp_seurat = ipf_seu_mac[,num_cells$cellid]
# 
# 
# ## use raw counts as input for scenic
# loom = SCopeLoomR::build_loom(paste0(working.dir,"/IPF_manuscript/data/ILD_combined_sct_rpca20230720_mac_rawcounts_100persubcluster_rmvprolif_scenic.loom"),
#                   dgem=tmp_seurat@assays$RNA@counts)
# 
# # loom = add_cell_annotation(loom,tmp_seurat@meta.data)
# 
# close_loom(loom)
```

## all in one figure

```{r}
regulon_auc1 = read.csv2(paste0(working.dir,"/IPF_manuscript/manuscriptV3/meta_data/ILD_combined_sct_rpca20230720_mac_rawcounts_100persubcluster_scenic_auc_mtx.csv"),sep = ",")
colnames(regulon_auc1) <- gsub("\\.", "", colnames(regulon_auc1))
regulonCol = colnames(regulon_auc1)[2:ncol(regulon_auc1)]
cells = regulon_auc1$Cell

regulon_auc1 = t(regulon_auc1) %>% as.data.frame()
colnames(regulon_auc1) = regulon_auc1[1,]
regulon_auc1 = regulon_auc1[2:nrow(regulon_auc1),]
regulon_auc1 = sapply(regulon_auc1,as.numeric)
rownames(regulon_auc1) = regulonCol

regulon_auc1 = as.matrix(regulon_auc1)
regulon_seu1 = ipf_seu_mac[,cells]

regulon_seu1[["AUC"]] = CreateAssayObject(data = regulon_auc1)

rm(regulonCol,cells)

DefaultAssay(regulon_seu1) = "AUC"
regulon_seu1$subcluster1 = ifelse(regulon_seu1$subcluster %in% c(7,13,20),20,as.character(regulon_seu1$subcluster))
regulon_seu1$subcluster1 = factor(regulon_seu1$subcluster1,levels = c(0,"4_0","4_1","4_2",6,8,10,11,20))

Idents(regulon_seu1) = "subcluster1"

regulon_seu1 = ScaleData(regulon_seu1,assay = "AUC")

# scenic_keepprolif_deg = FindAllMarkers(regulon_seu1,assay = "AUC",logfc.threshold = 0)

# write.csv(scenic_keepprolif_deg,file = paste0(working.dir,"/IPF_manuscript/meta_data/ILD_combined_sct_rpca20230720_mac_rawcounts_100persubcluster_scenic_auc_mtx_dea.csv"))
# DoHeatmap(regulon_seu1,features = plot_genes1[plot_genes1$cluster %in% c(20),"gene"] %>% unique())

scenic_keepprolif_deg = read.csv(file = paste0(working.dir,"/IPF_manuscript/meta_data/ILD_combined_sct_rpca20230720_mac_rawcounts_100persubcluster_scenic_auc_mtx_dea.csv"))

DoHeatmap(regulon_seu1,features = scenic_keepprolif_deg[scenic_keepprolif_deg$avg_log2FC>0 & scenic_keepprolif_deg$p_val_adj < 0.01, ] %>% group_by(cluster) %>% top_n(n = 5, wt = avg_log2FC) %>% .$gene %>% unique() )

p = DotPlot(regulon_seu1,features = scenic_keepprolif_deg[scenic_keepprolif_deg$avg_log2FC>0 & scenic_keepprolif_deg$p_val_adj < 1, ] %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC) %>% .$gene %>% unique())+
  coord_flip()

plot_label = c("0" = "0",
               "4_0" = "4_0",
               "4_1" = "4_1",
               "4_2" = "4_2",
               "6" = "6",
               "8" = "8",
               "10" = "10",
               "11" = "11",
               "20" = "7,13,20"
               )

p4 = ggplot(p$data,aes(x=features.plot,y=id))+
  geom_point(aes(color=avg.exp.scaled))+
  scale_y_discrete(labels = mac_label)+
  scale_color_gradientn(colours  = c("#a8dadc","white","#9d0208"))+
  # coord_flip()+
  xlab("")+
  ylab("")+
  theme_classic()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),
        axis.text = element_text(size = 8),
        axis.line = element_blank(),
        # axis.ticks.y = element_blank(),
        # axis.text.y = element_blank(),
        panel.border = element_rect(color = "black",size=0.8,fill = NA),
        legend.position = "right",
        legend.text = element_text(size = 8,colour = "black"),
        legend.title = element_text(size = 8,colour = "black"),
        legend.box = "vertical",
        legend.box.margin = margin(-20,-20,-20,-11))+
  guides(size = guide_legend(order = 2,title = "% of exp. cells"),
         color = guide_colorbar(order = 2,title = "Regulon activity",barwidth = 0.5,barheight = 3))
# dev.off()
```


## combine figures

```{r}

pdf(file = paste0(ms_dir,"/figs2e_mac_regulon_",ms_date,".pdf"),paper = "a4",width = 7,height = 3)

plot(p4)

dev.off()

p4
```

# session

```{r,results='asis'}
sessionInfo()
```

